id: I5ACF727B
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T17:24:20.492756'
last_modified: '2022-05-27T17:24:20.492768'
parser: null
source_metadata:
  title: 'MSV 1,16: Adhikaraṇavastu'
  language: bo
  base:
    fB5DA:
      title: Adhikaraṇavastu
      base_file: fB5DA.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
